In [3]:
#Problem 1

import numpy as np

def mult(A,B):
    return np.dot(A,B)

A = np.array([[3,-1,4],[1,5,-9]])
B = np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])

print(mult(A,B))


[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [4]:
#Problem 2

def poly(A):
    A_sq = np.dot(A,A)
    A_cu = np.dot(A, A_sq)
    return -1*A_cu + 9*A_sq - 15*A

A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
print(poly(A))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
#Problem 3

#Write a function that defines the functions as NumPy arrays.

def createA(x):
    I = np.ones((x,x), dtype=np.int)
    return np.triu(I)

def createB(x):
    I = np.ones((x,x), dtype=np.int)
    lower = -1*(np.tril(I))
    upper = 5*(np.triu(I))
    diagonal = np.diag(I)
    diag_only = -5*(np.diag(diagonal))
    return lower+upper+diag_only

A = createA(7)
B = createB(7)

print(A)
print(B)

#Calculate the matrix product ABA. Change the data type fo the resulting matrix to np.int64.

def multAB(A,B):
    AB = np.dot(A,B)
    ABA = np.dot(AB,A)
    return ABA.astype(np.int64) 

print(multAB(A,B))

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]
[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]
[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


In [21]:
#Problem 4

def setzero(X):
    Xstar = np.copy(X)
    mask = Xstar < 0
    Xstar[mask] = 0
    return Xstar

#test case:
array = np.array([[1,3,-5]])
print(setzero(array))

[[1 3 0]]


In [32]:
#Problem 5

A = np.array([[0,2,4],[1,3,5]])
Atrans = np.transpose(A)

B1 = np.ones((3,3),dtype=np.int)
B2 = B1*3
B = np.tril(B2)

C = np.diag([-2,-2,-2])

zeros1 = np.zeros((3,3), dtype=np.int)
zeros2 = np.zeros((5,2), dtype=np.int)
zeros3 = np.zeros((2,3), dtype=np.int)

I = np.eye(3)

Col1 = np.vstack((zeros1,A,B))
Col2 = np.vstack((Atrans, zeros2))
Col3 = np.vstack((I, zeros3, C))

print(np.hstack((Col1, Col2, Col3)))




[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


In [48]:
#Problem 6

def rowstoch(A):
    sums = A.sum(axis=1).reshape((2,1))
    return A/sums

#Test case:
A = np.array([[3,-1,4],[1,5,-9]])
print(rowstoch(A))

[[ 0.5        -0.16666667  0.66666667]
 [-0.33333333 -1.66666667  3.        ]]


In [79]:
#Problem 7

grid = np.load("grid.npy")
maxima = []

horizontal_max = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
maxima.append(horizontal_max)

vertical_max = np.max(grid[:-3,:]*grid[1:-2,:]*grid[2:-1,:]*grid[3:,:])
maxima.append(vertical_max)

leftdiag_max = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
maxima.append(leftdiag_max)

rightdiag_max = np.max(grid[:-3,3:]*grid[1:-2,2:-1]*grid[2:-1,1:-2]*grid[3:,:-3])
maxima.append(rightdiag_max)

print(max(maxima))

70600674
