## Part A

In [1]:
# Import packages
import numpy as np
import numpy.linalg as lin
import scipy.stats as sts
import scipy.integrate as intgr
import scipy.optimize as opt
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
# Import data
data = np.loadtxt('data/MacroSeries.txt', delimiter=',')
c = data[:,0]
k = data[:,1]
w = data[:,2]
r = data[:,3]

In [3]:
# Function for obtaining z values
def get_z(w, k, alpha):
    z = np.zeros(len(w))
    z = np.log(w/((1-alpha)*(k**alpha)))
    return z

In [4]:
def log_likelihood(w, k, alpha, rho, mu, sigma):
    z = get_z(w,k,alpha)
    mean = np.zeros(len(z))
    for i in range(len(mean)):
        if i == 0:
            mean[i] = mu
        else:
            mean[i] = rho*z[i-1] + (1-rho)*mu
    pdf_vals = (1/(sigma * np.sqrt(2 * np.pi))*np.exp( - (z - mean)**2 / (2 * sigma**2)))
    pdf_vals[np.isclose(pdf_vals, np.zeros_like(pdf_vals), atol=1e-10)] = 1e-10
    ln_pdf_vals = np.log(pdf_vals ,where=(pdf_vals > 0))
    log_lik_val = np.sum(ln_pdf_vals)
    return log_lik_val 

In [5]:
def crit(params, *args):
    alpha, rho, mu, sigma = params
    w, k = args
    log_lik_val = log_likelihood(w, k, alpha, rho, mu, sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val

In [6]:
alpha0 = 0.50
rho0 = 0.75
mu0 = 5.0
sigma0 = 0.80
params_init = np.array([alpha0, rho0, mu0, sigma0])
args = (w, k)

results = opt.minimize(crit, params_init, args=(args), method='L-BFGS-B',
                       bounds=((1e-10, 1-1e-10),(-1+1e-10, 1-1e-10),
                               (1e-10, None), (1e-10, None)))

alpha_mle, rho_mle, mu_mle, sigma_mle = results.x
log_lik_mle = log_likelihood(w, k, alpha_mle, rho_mle, mu_mle, sigma_mle)
alpha_MLE, rho_MLE, mu_MLE, sigma_MLE = results.x
print("INITIAL CONDITIONS:")
print("alpha0 = "+str(alpha0))
print("rho0 = "+str(rho0))
print("mu0 = "+str(mu0))
print("sigma0 = "+str(sigma0))
print("")
print("RESULTS:")
print("alpha_MLE = "+str(alpha_MLE))
print("rho_MLE = "+str(rho_MLE))
print("mu_MLE = "+str(mu_MLE))
print("sigma_MLE = "+str(sigma_MLE))
alpha_MLE, rho_MLE, mu_MLE, sigma_MLE = results.x
print("")
print("HESSIAN MATRIX")
print(results.hess_inv.todense())
print("")
print(results)

INITIAL CONDITIONS:
alpha0 = 0.5
rho0 = 0.75
mu0 = 5.0
sigma0 = 0.8

RESULTS:
alpha_MLE = 0.457517689185
rho_MLE = 0.720488145371
mu_MLE = 9.52270048591
sigma_MLE = 0.0919962533974

HESSIAN MATRIX
[[  1.08233514e+01   1.36717960e+00  -1.46227736e+02  -4.44524777e-01]
 [  1.36717960e+00   2.62635031e+00  -1.72705944e+01  -6.69951387e-02]
 [ -1.46227736e+02  -1.72705944e+01   1.97618382e+03   6.00029132e+00]
 [ -4.44524777e-01  -6.69951387e-02   6.00029131e+00   1.84197963e-02]]

      fun: -96.706908072584142
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([  1.07576170e-03,  -3.83693077e-05,   7.38964445e-05,
         5.25801624e-04])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 295
      nit: 35
   status: 0
  success: True
        x: array([ 0.45751769,  0.72048815,  9.52270049,  0.09199625])


## Part B

In [7]:
# Function for obtaining z values
def get_z(r, k, alpha):
    z = np.log(r/((alpha)*(k**(alpha-1))))
    return z

def log_likelihood(r, k, alpha, rho, mu, sigma):
    z = get_z(r,k,alpha)
    mean = np.zeros(len(z))
    for i in range(len(mean)):
        if i == 0:
            mean[i] = mu
        else:
            mean[i] = rho*z[i-1] + (1-rho)*mu
    pdf_vals = (1/(sigma * np.sqrt(2 * np.pi))*np.exp( - (z - mean)**2 / (2 * sigma**2)))
    pdf_vals[np.isclose(pdf_vals, np.zeros_like(pdf_vals), atol=1e-10)] = 1e-10
    ln_pdf_vals = np.log(pdf_vals ,where=(pdf_vals > 0))
    log_lik_val = np.sum(ln_pdf_vals)
    return log_lik_val 

def crit(params, *args):
    alpha, rho, mu, sigma = params
    r, k = args
    log_lik_val = log_likelihood(r, k, alpha, rho, mu, sigma)
    neg_log_lik_val = -log_lik_val
    return neg_log_lik_val

alpha0 = 0.50
rho0 = 0.75
mu0 = 5.0
sigma0 = 0.80
params_init = np.array([alpha0, rho0, mu0, sigma0])
args = (r, k)

results = opt.minimize(crit, params_init, args=(args), method='L-BFGS-B',
                       bounds=((1e-10, 1-1e-10),(-1+1e-10, 1-1e-10),
                               (1e-10, None), (1e-10, None)))

alpha_mle, rho_mle, mu_mle, sigma_mle = results.x
log_lik_mle = log_likelihood(r, k, alpha_mle, rho_mle, mu_mle, sigma_mle)
alpha_MLE, rho_MLE, mu_MLE, sigma_MLE = results.x
print("INITIAL CONDITIONS:")
print("alpha0 = "+str(alpha0))
print("rho0 = "+str(rho0))
print("mu0 = "+str(mu0))
print("sigma0 = "+str(sigma0))
print("")
print("RESULTS:")
print("alpha_MLE = "+str(alpha_MLE))
print("rho_MLE = "+str(rho_MLE))
print("mu_MLE = "+str(mu_MLE))
print("sigma_MLE = "+str(sigma_MLE))
alpha_MLE, rho_MLE, mu_MLE, sigma_MLE = results.x
print("")
print("HESSIAN MATRIX")
print(results.hess_inv.todense())
print("")
print(results)

INITIAL CONDITIONS:
alpha0 = 0.5
rho0 = 0.75
mu0 = 5.0
sigma0 = 0.8

RESULTS:
alpha_MLE = 0.457466530472
rho_MLE = 0.720534302462
mu_MLE = 9.37119012628
sigma_MLE = 0.0919956454084

HESSIAN MATRIX
[[  2.10331696e+01   7.04342389e+00  -3.76372080e+02  -2.15558358e+00]
 [  7.04342389e+00   1.90308420e+02  -1.61651620e+02   5.10899047e+00]
 [ -3.76372080e+02  -1.61651620e+02   6.74163780e+03   3.74659667e+01]
 [ -2.15558358e+00   5.10899047e+00   3.74659667e+01   4.02340718e-01]]

      fun: -96.706907988593287
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 0.03154099,  0.00178062,  0.00169535, -0.01384564])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 260
      nit: 27
   status: 0
  success: True
        x: array([ 0.45746653,  0.7205343 ,  9.37119013,  0.09199565])


## Part C

In [8]:
r = 1
k = 7500000
z0 = 10
z1 = np.log(r/(alpha_MLE*k**(alpha_MLE-1)))
z1
#This gives the z1 value that is equivalent to r=1.

9.3705807571941744

In [9]:
mu = rho_MLE*z0 + (1-rho_MLE)*mu_MLE
p = 1-sts.norm.cdf(z1,loc=mu,scale=sigma_MLE)
print(p)

0.999999592268


There is over a 99% probability that the interest rate will be greater than 1 in the next period.